import pygame

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60
TILE_SIZE = 48

COLORS = {
    "black": (0, 0, 0),
    "white": (255, 255, 255),
    "red": (220, 50, 50),
    "green": (50, 200, 50),
    "blue": (50, 100, 220),
    "yellow": (230, 210, 50),
    "orange": (230, 130, 30),
    "purple": (150, 50, 200),
    "gray": (120, 120, 120),
    "dark_gray": (60, 60, 60),
    "light_gray": (180, 180, 180),
    "dark_red": (130, 20, 20),
    "dark_green": (20, 100, 20),
    "brown": (139, 90, 43),
    "cyan": (50, 200, 200),
    "pink": (255, 100, 150),
    "blood": (160, 20, 20),
    "safe_green": (30, 180, 60),
    "floor_dark": (50, 55, 60),
    "floor_light": (65, 70, 75),
    "wall": (80, 80, 90),
    "wall_top": (100, 100, 115),
    "door": (160, 100, 40),
}

CHARACTER_DATA = {
    "chef": {
        "name": "Chef",
        "desc": "O Cozinheiro - Tanque",
        "color": (50, 120, 220),
        "hp": 150,
        "speed": 2.8,
        "ability": "Tiro duplo",
        "ability_desc": "Dispara 2 tiros simultaneamente",
        "ability_cooldown": 8000,
    },
    "carlos": {
        "name": "Carlos",
        "desc": "O Mecanico - Equilibrado",
        "color": (220, 180, 50),
        "hp": 100,
        "speed": 3.2,
        "ability": "Reparo rapido",
        "ability_desc": "Conserta 30 HP em 2 segundos",
        "ability_cooldown": 15000,
    },
    "raquel": {
        "name": "Raquel",
        "desc": "A Repórter - Rapida",
        "color": (220, 60, 100),
        "hp": 80,
        "speed": 3.8,
        "ability": "Corrida frenetica",
        "ability_desc": "Velocidade x2 por 4 segundos",
        "ability_cooldown": 12000,
    },
    "nicolas": {
        "name": "Nicolas",
        "desc": "O Apostador - Sortudo",
        "color": (60, 180, 80),
        "hp": 100,
        "speed": 3.0,
        "ability": "Sorte grande",
        "ability_desc": "30% chance de tiro critico (3x dano)",
        "ability_cooldown": 10000,
    },
}

WEAPON_DATA = {
    "pistol": {
        "name": "Pistola",
        "damage": 15,
        "fire_rate": 300,
        "magazine": 15,
        "max_ammo": 120,
        "spread": 3,
        "bullet_speed": 12,
        "bullet_color": (255, 255, 100),
        "size": 8,
        "auto": False,
        "pickup_chance": 0,
    },
    "shotgun": {
        "name": "Escopeta",
        "damage": 8,
        "fire_rate": 800,
        "magazine": 6,
        "max_ammo": 40,
        "spread": 25,
        "bullet_speed": 10,
        "bullet_color": (255, 180, 50),
        "size": 6,
        "pellets": 6,
        "auto": False,
        "pickup_chance": 0.15,
    },
    "smg": {
        "name": "MP5",
        "damage": 10,
        "fire_rate": 80,
        "magazine": 30,
        "max_ammo": 180,
        "spread": 8,
        "bullet_speed": 14,
        "bullet_color": (100, 255, 200),
        "size": 5,
        "auto": True,
        "pickup_chance": 0.15,
    },
    "rifle": {
        "name": "AK-47",
        "damage": 18,
        "fire_rate": 120,
        "magazine": 30,
        "max_ammo": 150,
        "spread": 5,
        "bullet_speed": 16,
        "bullet_color": (255, 220, 100),
        "size": 6,
        "auto": True,
        "pickup_chance": 0.12,
    },
    "sniper": {
        "name": "AWP",
        "damage": 80,
        "fire_rate": 1200,
        "magazine": 5,
        "max_ammo": 20,
        "spread": 1,
        "bullet_speed": 25,
        "bullet_color": (255, 50, 50),
        "size": 4,
        "auto": False,
        "pickup_chance": 0.08,
    },
    "grenade_launcher": {
        "name": "Lanca-granadas",
        "damage": 60,
        "fire_rate": 1500,
        "magazine": 4,
        "max_ammo": 12,
        "spread": 2,
        "bullet_speed": 8,
        "bullet_color": (200, 200, 50),
        "size": 8,
        "explosive": True,
        "explosion_radius": 100,
        "auto": False,
        "pickup_chance": 0.05,
    },
}

ENEMY_DATA = {
    "common": {
        "name": "Zumbi Comum",
        "hp": 30,
        "damage": 10,
        "speed": 1.2,
        "color": (80, 120, 60),
        "size": 14,
        "attack_range": 30,
        "attack_cooldown": 1000,
        "points": 10,
    },
    "boomer": {
        "name": "Boomer",
        "hp": 60,
        "damage": 15,
        "speed": 0.8,
        "color": (100, 180, 60),
        "size": 22,
        "attack_range": 50,
        "attack_cooldown": 2000,
        "points": 50,
        "explode_on_death": True,
        "explode_radius": 120,
        "attracts_horde": True,
        "vomit_chance": 0.3,
    },
    "smoker": {
        "name": "Smoker",
        "hp": 50,
        "damage": 8,
        "speed": 1.0,
        "color": (140, 140, 160),
        "size": 16,
        "attack_range": 200,
        "attack_cooldown": 3000,
        "points": 50,
        "tongue_range": 200,
        "tongue_damage": 5,
        "pull_speed": 3,
    },
    "hunter": {
        "name": "Hunter",
        "hp": 40,
        "damage": 25,
        "speed": 2.5,
        "color": (200, 60, 40),
        "size": 16,
        "attack_range": 250,
        "attack_cooldown": 4000,
        "points": 60,
        "pounce_speed": 8,
        "pounce_damage": 30,
        "pounce_stun": 1500,
    },
    "tank": {
        "name": "Tank",
        "hp": 500,
        "damage": 40,
        "speed": 1.5,
        "color": (100, 70, 50),
        "size": 30,
        "attack_range": 40,
        "attack_cooldown": 1200,
        "points": 200,
        "charge_speed": 5,
        "charge_damage": 60,
    },
    "witch": {
        "name": "Witch",
        "hp": 150,
        "damage": 80,
        "speed": 0.0,
        "color": (200, 100, 150),
        "size": 18,
        "attack_range": 40,
        "attack_cooldown": 2000,
        "points": 100,
        "frightened_range": 150,
        "cry_range": 100,
        "wander_speed": 0.8,
    },
}

CAMPAIGN = {
    "name": "Left 4 Dead 2D",
    "chapters": [
        {
            "name": "De Subtractis",
            "subtitle": "O Shopping Abandonado",
            "description": "Chegamos ao shopping... nao sobrou ninguem.",
            "width": 80,
            "height": 60,
            "safe_room_waves": 2,
            "horde_waves": 4,
            "horde_size_base": 15,
            "horde_growth": 8,
            "special_spawn_rate": 0.15,
            "item_spawn_rate": 0.03,
            "has_tank": True,
            "has_witch": True,
            "finale_waves": 3,
            "finale Horde_size": 40,
        },
        {
            "name": "A Praga",
            "subtitle": "O Hospital Infestado",
            "description": "O hospital esta tomado... cuidado com as Witches.",
            "width": 90,
            "height": 70,
            "safe_room_waves": 3,
            "horde_waves": 5,
            "horde_size_base": 20,
            "horde_growth": 10,
            "special_spawn_rate": 0.20,
            "item_spawn_rate": 0.025,
            "has_tank": True,
            "has_witch": True,
            "finale_waves": 4,
            "finale_horde_size": 55,
        },
        {
            "name": "O Preco",
            "subtitle": "A Prisao Desolada",
            "description": "A saida e perto... mas a horda final vem.",
            "width": 100,
            "height": 80,
            "safe_room_waves": 3,
            "horde_waves": 6,
            "horde_size_base": 25,
            "horde_growth": 12,
            "special_spawn_rate": 0.25,
            "item_spawn_rate": 0.02,
            "has_tank": True,
            "has_witch": True,
            "finale_waves": 5,
            "finale_horde_size": 70,
        },
    ],
}

ITEM_DATA = {
    "medkit": {"name": "Kit Medico", "color": (220, 40, 40), "heal": 40, "size": 12},
    "pills": {"name": "Pilulas", "color": (220, 220, 220), "heal": 20, "size": 8},
    "ammo": {"name": "Municao", "color": (200, 170, 50), "ammo_amount": 30, "size": 8},
    "adrenaline": {"name": "Adrenalina", "color": (50, 220, 220), "speed_boost": 1.5, "duration": 5000, "size": 10},
    "weapon_shotgun": {"name": "Escopeta", "color": (180, 120, 40), "weapon_id": "shotgun", "size": 10},
    "weapon_smg": {"name": "MP5", "color": (40, 180, 120), "weapon_id": "smg", "size": 10},
    "weapon_rifle": {"name": "AK-47", "color": (180, 140, 40), "weapon_id": "rifle", "size": 10},
    "weapon_sniper": {"name": "AWP", "color": (180, 40, 40), "weapon_id": "sniper", "size": 10},
    "weapon_grenade": {"name": "Lanca-granadas", "color": (180, 180, 40), "weapon_id": "grenade_launcher", "size": 10},
}

TILE_TYPES = {
    0: "floor",
    1: "wall",
    2: "safe_floor",
    3: "door",
    4: "spawn_point",
    5: "horde_trigger",
    6: "item_spawn",
    7: "finale_trigger",
}
